version: '3'
services:
  # mongodb:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_DATABASE: nombre_de_la_base_de_datos
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data:/data/db
  web:
    image: williamferreira1207/proy-final:1.0
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: williamferreira1207/db-proy-final:1.0
    environment:
      - MONGO_INITDB_DATABASE=mongo
    volumes:
      - ./data:/data/db