version: 2.1

jobs:
  desarrollo:
    docker:
      - image: node:16.13
    environment:
      REPO_URL: "/"
    steps:
      - add_ssh_keys:
            fingerprints:
              - "a5:c9:c5:32:20:7f:5e:26:a1:f8:d7:e3:b0:e8:c3:67"
      - checkout
      - run:
          name: Development Tests
          command: |
            npm install
            # npm run build
            # npm test
      - run:
          name: Create and Push Branch
          command: |
            git config --global user.email "chawiwifr@gmail.com"
            git config --global user.name "CircleCI Job"
            git fetch origin Desarrollo
            git checkout Desarrollo
            git pull origin Desarrollo
            # Use GitHub API to create a pull request
            curl -X POST -H "Authorization: token $GIT_TOKEN" \
            -d '{"title": "Merge Desarrollo into QA", "head": "Desarrollo", "base": "QA"}' \
            https://api.github.com/repos/WilliamBPFR/RepositorioConstruccion/pulls

  qa:
    docker:
      - image: node:16.13
    environment:
      GIT_TOKEN: $GIT_TOKEN
    steps:
      - checkout
      - run:
          name: QA Tests
          command: |
            npx eslint
            npx jest
      - run:
          name: Create and Push Branch
          command: |
            git config --global user.email "chawiwifr@gmail.com"
            git config --global user.name "CircleCI Job"
            git fetch origin QA
            git checkout QA
            git pull origin QA
            # Use GitHub API to create a pull request
            curl -X POST -H "Authorization: token $GIT_TOKEN" \
            -d '{"title": "Merge QA into Produccion", "head": "QA", "base": "Produccion"}' \
            https://api.github.com/repos/WilliamBPFR/RepositorioConstruccion/pulls

  produccion:
    docker:
      - image: node:16.13
    environment:
      GIT_TOKEN: $GIT_TOKEN
    steps:
      - checkout
      - run:
          name: Produccion Tests
          command: |
            #npm run test-file -- Login.test.js

workflows:
  version: 2
  build:
    jobs:
      - desarrollo:
          filters:
            branches:
              only:
                - Desarrollo
      - qa:
          filters:
            branches:
              only:
                - QA
      - produccion:
          requires:
            - qa
          filters:
            branches:
              only:
                - Produccion